# Competencia en Kaggle: Titanic: Machine Learning from Disaster

# 1. Crea una cuenta en Kaggle https://www.kaggle.com/

# 2. Ejecuta las celdas

In [1]:
import pandas as pd

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
validate = pd.read_csv('gender_submission.csv')

# Drop features-... is this good?

In [2]:
train = train.drop(['Name','SibSp', 'Ticket', 'Cabin', 'Embarked'],axis=1)
test = test.drop(['Name','SibSp', 'Ticket', 'Cabin', 'Embarked'],axis=1)

train

     PassengerId  Survived  Pclass     Sex   Age  Parch      Fare
0              1         0       3    male  22.0      0    7.2500
1              2         1       1  female  38.0      0   71.2833
2              3         1       3  female  26.0      0    7.9250
3              4         1       1  female  35.0      0   53.1000
4              5         0       3    male  35.0      0    8.0500
5              6         0       3    male   NaN      0    8.4583
6              7         0       1    male  54.0      0   51.8625
7              8         0       3    male   2.0      1   21.0750
8              9         1       3  female  27.0      2   11.1333
9             10         1       2  female  14.0      0   30.0708
10            11         1       3  female   4.0      1   16.7000
11            12         1       1  female  58.0      0   26.5500
12            13         0       3    male  20.0      0    8.0500
13            14         0       3    male  39.0      5   31.2750
14            15         0       3  female  14.0      0    7.8542
15            16         1       2  female  55.0      0   16.0000
16            17         0       3    male   2.0      1   29.1250
17            18         1       2    male   NaN      0   13.0000
18            19         0       3  female  31.0      0   18.0000
19            20         1       3  female   NaN      0    7.2250
20            21         0       2    male  35.0      0   26.0000
21            22         1       2    male  34.0      0   13.0000
22            23         1       3  female  15.0      0    8.0292
23            24         1       1    male  28.0      0   35.5000
24            25         0       3  female   8.0      1   21.0750
25            26         1       3  female  38.0      5   31.3875
26            27         0       3    male   NaN      0    7.2250
27            28         0       1    male  19.0      2  263.0000
28            29         1       3  female   NaN      0    7.8792
29            30         0       3    male   NaN      0    7.8958
..           ...       ...     ...     ...   ...    ...       ...
861          862         0       2    male  21.0      0   11.5000
862          863         1       1  female  48.0      0   25.9292
863          864         0       3  female   NaN      2   69.5500
864          865         0       2    male  24.0      0   13.0000
865          866         1       2  female  42.0      0   13.0000
866          867         1       2  female  27.0      0   13.8583
867          868         0       1    male  31.0      0   50.4958
868          869         0       3    male   NaN      0    9.5000
869          870         1       3    male   4.0      1   11.1333
870          871         0       3    male  26.0      0    7.8958
871          872         1       1  female  47.0      1   52.5542
872          873         0       1    male  33.0      0    5.0000
873          874         0       3    male  47.0      0    9.0000
874          875         1       2  female  28.0      0   24.0000
875          876         1       3  female  15.0      0    7.2250
876          877         0       3    male  20.0      0    9.8458
877          878         0       3    male  19.0      0    7.8958
878          879         0       3    male   NaN      0    7.8958
879          880         1       1  female  56.0      1   83.1583
880          881         1       2  female  25.0      1   26.0000
881          882         0       3    male  33.0      0    7.8958
882          883         0       3  female  22.0      0   10.5167
883          884         0       2    male  28.0      0   10.5000
884          885         0       3    male  25.0      0    7.0500
885          886         0       3  female  39.0      5   29.1250
886          887         0       2    male  27.0      0   13.0000
887          888         1       1  female  19.0      0   30.0000
888          889         0       3  female   NaN      2   23.4500
889          890         1       1    male  26.0      0   30.0000
890          891         0       3    male  32.0      0    7.7500

[891 rows x 7 columns]

# Sex mapping 1 - male, 0 - female

In [3]:
train['Sex_binary']=train['Sex'].map({'male':1,'female':0})
test['Sex_binary']=test['Sex'].map({'male':1,'female':0})

# Age cleaning

In [4]:
train['Age'] = train['Age'].fillna(29)
test['Age'] = test['Age'].fillna(29)

In [5]:
features = ['Pclass','Age','Sex_binary', 'Fare', 'Parch']
target = 'Survived'

In [6]:
train[features].head(3)

   Pclass   Age  Sex_binary     Fare  Parch
0       3  22.0           1   7.2500      0
1       1  38.0           0  71.2833      0
2       3  26.0           0   7.9250      0

In [7]:
import numpy as np

In [8]:
X_train = np.array(train[features])
X_train

array([[ 3.    , 22.    ,  1.    ,  7.25  ,  0.    ],
       [ 1.    , 38.    ,  0.    , 71.2833,  0.    ],
       [ 3.    , 26.    ,  0.    ,  7.925 ,  0.    ],
       ...,
       [ 3.    , 29.    ,  0.    , 23.45  ,  2.    ],
       [ 1.    , 26.    ,  1.    , 30.    ,  0.    ],
       [ 3.    , 32.    ,  1.    ,  7.75  ,  0.    ]])

In [9]:
y_train = np.array(train[target])
y_train = y_train.reshape(-1,1)

In [10]:
# Import keras modules
from keras.models import Sequential
from keras.layers import Dense
from keras.initializers import glorot_normal
from keras.optimizers import SGD

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

In [11]:
model = Sequential()
numNeurons = 4
model.add(Dense(numNeurons, input_dim=len(features), activation='relu', kernel_initializer="uniform"))
model.add(Dense(1, activation='sigmoid', kernel_initializer="uniform"))
#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['mae']) old

sgd = SGD(lr=0.08, decay=1e-6, momentum=0.7, nesterov=True)

model.compile(loss='mean_squared_logarithmic_error', optimizer=sgd, metrics=['mae'])

In [12]:
model.fit(X_train, y_train, epochs=200, batch_size=20)
#score = model.evaluate(X_test, y_test, batch_size=25)
#score

Epoch 1/200
891/891 [==============================] - 0s 490us/step - loss: 0.1115 - mean_absolute_error: 0.4422
Epoch 2/200
891/891 [==============================] - 0s 130us/step - loss: 0.1027 - mean_absolute_error: 0.4080
Epoch 3/200
891/891 [==============================] - 0s 109us/step - loss: 0.1022 - mean_absolute_error: 0.4032
Epoch 4/200
891/891 [==============================] - 0s 226us/step - loss: 0.1022 - mean_absolute_error: 0.3999
Epoch 5/200
891/891 [==============================] - 0s 127us/step - loss: 0.1025 - mean_absolute_error: 0.4019
Epoch 6/200
891/891 [==============================] - 0s 136us/step - loss: 0.1011 - mean_absolute_error: 0.4054
Epoch 7/200
891/891 [==============================] - 0s 129us/step - loss: 0.1001 - mean_absolute_error: 0.3966
Epoch 8/200
891/891 [==============================] - 0s 119us/step - loss: 0.1011 - mean_absolute_error: 0.3980
Epoch 9/200
891/891 [==============================] - 0s 113us/step - loss: 0.1014 - mean_absolute_error: 0.3982
Epoch 10/200
891/891 [==============================] - 0s 114us/step - loss: 0.1009 - mean_absolute_error: 0.4022
Epoch 11/200
891/891 [==============================] - 0s 107us/step - loss: 0.1000 - mean_absolute_error: 0.3941
Epoch 12/200
891/891 [==============================] - 0s 106us/step - loss: 0.1004 - mean_absolute_error: 0.4030
Epoch 13/200
891/891 [==============================] - 0s 157us/step - loss: 0.1007 - mean_absolute_error: 0.3873
Epoch 14/200
891/891 [==============================] - 0s 147us/step - loss: 0.0998 - mean_absolute_error: 0.3975
Epoch 15/200
891/891 [==============================] - 0s 170us/step - loss: 0.1004 - mean_absolute_error: 0.3977
Epoch 16/200
891/891 [==============================] - 0s 139us/step - loss: 0.1006 - mean_absolute_error: 0.4013
Epoch 17/200
891/891 [==============================] - 0s 133us/step - loss: 0.1001 - mean_absolute_error: 0.3908
Epoch 18/200
891/891 [==============================] - 0s 139us/step - loss: 0.0993 - mean_absolute_error: 0.3933
Epoch 19/200
891/891 [==============================] - 0s 150us/step - loss: 0.0995 - mean_absolute_error: 0.3951
Epoch 20/200
891/891 [==============================] - 0s 111us/step - loss: 0.1001 - mean_absolute_error: 0.3961
Epoch 21/200
891/891 [==============================] - 0s 110us/step - loss: 0.0988 - mean_absolute_error: 0.3985
Epoch 22/200
891/891 [==============================] - 0s 101us/step - loss: 0.0994 - mean_absolute_error: 0.3976
Epoch 23/200
891/891 [==============================] - 0s 105us/step - loss: 0.0984 - mean_absolute_error: 0.3939
Epoch 24/200
891/891 [==============================] - 0s 146us/step - loss: 0.0983 - mean_absolute_error: 0.3927
Epoch 25/200
891/891 [==============================] - 0s 114us/step - loss: 0.0996 - mean_absolute_error: 0.4049
Epoch 26/200
891/891 [==============================] - 0s 131us/step - loss: 0.0990 - mean_absolute_error: 0.3962
Epoch 27/200
891/891 [==============================] - 0s 111us/step - loss: 0.1002 - mean_absolute_error: 0.4014
Epoch 28/200
891/891 [==============================] - 0s 115us/step - loss: 0.1006 - mean_absolute_error: 0.4032
Epoch 29/200
891/891 [==============================] - 0s 110us/step - loss: 0.0976 - mean_absolute_error: 0.4005
Epoch 30/200
891/891 [==============================] - 0s 121us/step - loss: 0.0974 - mean_absolute_error: 0.3948
Epoch 31/200
891/891 [==============================] - 0s 119us/step - loss: 0.0967 - mean_absolute_error: 0.3931
Epoch 32/200
891/891 [==============================] - 0s 99us/step - loss: 0.0982 - mean_absolute_error: 0.3989
Epoch 33/200
891/891 [==============================] - 0s 92us/step - loss: 0.0981 - mean_absolute_error: 0.3934
Epoch 34/200
891/891 [==============================] - 0s 116us/step - loss: 0.0970 - mean_absolute_error: 0.3942
Epoch 35/200
891/891 [==============================] - 0s 143us/step - loss: 0.0961 - mean_absolute_error: 0.3942
Epoch 36/200
891/891 [==============================] - 0s 103us/step - loss: 0.0980 - mean_absolute_error: 0.3924
Epoch 37/200
891/891 [==============================] - 0s 129us/step - loss: 0.0953 - mean_absolute_error: 0.3894
Epoch 38/200
891/891 [==============================] - 0s 110us/step - loss: 0.0939 - mean_absolute_error: 0.3849
Epoch 39/200
891/891 [==============================] - 0s 134us/step - loss: 0.0989 - mean_absolute_error: 0.3921
Epoch 40/200
891/891 [==============================] - 0s 155us/step - loss: 0.0960 - mean_absolute_error: 0.3850
Epoch 41/200
891/891 [==============================] - 0s 123us/step - loss: 0.0962 - mean_absolute_error: 0.3952
Epoch 42/200
891/891 [==============================] - 0s 147us/step - loss: 0.0978 - mean_absolute_error: 0.3896
Epoch 43/200
891/891 [==============================] - 0s 103us/step - loss: 0.0941 - mean_absolute_error: 0.3880
Epoch 44/200
891/891 [==============================] - 0s 100us/step - loss: 0.0971 - mean_absolute_error: 0.3910
Epoch 45/200
891/891 [==============================] - 0s 90us/step - loss: 0.0966 - mean_absolute_error: 0.3903
Epoch 46/200
891/891 [==============================] - 0s 82us/step - loss: 0.0948 - mean_absolute_error: 0.3869
Epoch 47/200
891/891 [==============================] - 0s 78us/step - loss: 0.0935 - mean_absolute_error: 0.3842
Epoch 48/200
891/891 [==============================] - 0s 74us/step - loss: 0.0923 - mean_absolute_error: 0.3761
Epoch 49/200
891/891 [==============================] - 0s 72us/step - loss: 0.0971 - mean_absolute_error: 0.3916
Epoch 50/200
891/891 [==============================] - 0s 79us/step - loss: 0.0963 - mean_absolute_error: 0.3877
Epoch 51/200
891/891 [==============================] - 0s 62us/step - loss: 0.0949 - mean_absolute_error: 0.3819
Epoch 52/200
891/891 [==============================] - 0s 67us/step - loss: 0.0953 - mean_absolute_error: 0.3827
Epoch 53/200
891/891 [==============================] - 0s 69us/step - loss: 0.0937 - mean_absolute_error: 0.3814
Epoch 54/200
891/891 [==============================] - 0s 67us/step - loss: 0.0935 - mean_absolute_error: 0.3802
Epoch 55/200
891/891 [==============================] - 0s 92us/step - loss: 0.0944 - mean_absolute_error: 0.3800
Epoch 56/200
891/891 [==============================] - 0s 92us/step - loss: 0.0927 - mean_absolute_error: 0.3806
Epoch 57/200
891/891 [==============================] - 0s 78us/step - loss: 0.0922 - mean_absolute_error: 0.3794
Epoch 58/200
891/891 [==============================] - 0s 75us/step - loss: 0.0991 - mean_absolute_error: 0.3894
Epoch 59/200
891/891 [==============================] - 0s 74us/step - loss: 0.1305 - mean_absolute_error: 0.4954
Epoch 60/200
891/891 [==============================] - 0s 63us/step - loss: 0.1177 - mean_absolute_error: 0.4743
Epoch 61/200
891/891 [==============================] - 0s 85us/step - loss: 0.1147 - mean_absolute_error: 0.4642
Epoch 62/200
891/891 [==============================] - 0s 56us/step - loss: 0.1140 - mean_absolute_error: 0.4585
Epoch 63/200
891/891 [==============================] - 0s 57us/step - loss: 0.1138 - mean_absolute_error: 0.4579
Epoch 64/200
891/891 [==============================] - 0s 60us/step - loss: 0.1137 - mean_absolute_error: 0.4559
Epoch 65/200
891/891 [==============================] - 0s 66us/step - loss: 0.1137 - mean_absolute_error: 0.4566
Epoch 66/200
891/891 [==============================] - 0s 67us/step - loss: 0.1137 - mean_absolute_error: 0.4548
Epoch 67/200
891/891 [==============================] - 0s 63us/step - loss: 0.1137 - mean_absolute_error: 0.4544
Epoch 68/200
891/891 [==============================] - 0s 60us/step - loss: 0.1137 - mean_absolute_error: 0.4547
Epoch 69/200
891/891 [==============================] - 0s 63us/step - loss: 0.1137 - mean_absolute_error: 0.4547
Epoch 70/200
891/891 [==============================] - 0s 68us/step - loss: 0.1137 - mean_absolute_error: 0.4545
Epoch 71/200
891/891 [==============================] - 0s 67us/step - loss: 0.1137 - mean_absolute_error: 0.4548
Epoch 72/200

891/891 [==============================] - 0s 65us/step - loss: 0.1136 - mean_absolute_error: 0.4543
Epoch 73/200
891/891 [==============================] - 0s 56us/step - loss: 0.1136 - mean_absolute_error: 0.4538
Epoch 74/200
891/891 [==============================] - 0s 64us/step - loss: 0.1137 - mean_absolute_error: 0.4546
Epoch 75/200
891/891 [==============================] - 0s 51us/step - loss: 0.1137 - mean_absolute_error: 0.4552
Epoch 76/200
891/891 [==============================] - 0s 51us/step - loss: 0.1137 - mean_absolute_error: 0.4540
Epoch 77/200
891/891 [==============================] - 0s 54us/step - loss: 0.1137 - mean_absolute_error: 0.4548
Epoch 78/200
891/891 [==============================] - 0s 56us/step - loss: 0.1137 - mean_absolute_error: 0.4556
Epoch 79/200
891/891 [==============================] - 0s 55us/step - loss: 0.1136 - mean_absolute_error: 0.4548
Epoch 80/200
891/891 [==============================] - 0s 62us/step - loss: 0.1137 - mean_absolute_error: 0.4541
Epoch 81/200
891/891 [==============================] - 0s 60us/step - loss: 0.1137 - mean_absolute_error: 0.4544
Epoch 82/200
891/891 [==============================] - 0s 58us/step - loss: 0.1136 - mean_absolute_error: 0.4546
Epoch 83/200
891/891 [==============================] - 0s 59us/step - loss: 0.1137 - mean_absolute_error: 0.4539
Epoch 84/200
891/891 [==============================] - 0s 51us/step - loss: 0.1137 - mean_absolute_error: 0.4553
Epoch 85/200
891/891 [==============================] - 0s 63us/step - loss: 0.1137 - mean_absolute_error: 0.4535
Epoch 86/200
891/891 [==============================] - 0s 63us/step - loss: 0.1137 - mean_absolute_error: 0.4546
Epoch 87/200
891/891 [==============================] - 0s 63us/step - loss: 0.1137 - mean_absolute_error: 0.4545
Epoch 88/200
891/891 [==============================] - 0s 59us/step - loss: 0.1137 - mean_absolute_error: 0.4549
Epoch 89/200
891/891 [==============================] - 0s 58us/step - loss: 0.1137 - mean_absolute_error: 0.4554
Epoch 90/200
891/891 [==============================] - 0s 64us/step - loss: 0.1137 - mean_absolute_error: 0.4552
Epoch 91/200
891/891 [==============================] - 0s 63us/step - loss: 0.1137 - mean_absolute_error: 0.4543
Epoch 92/200
891/891 [==============================] - 0s 63us/step - loss: 0.1137 - mean_absolute_error: 0.4552
Epoch 93/200
891/891 [==============================] - 0s 61us/step - loss: 0.1137 - mean_absolute_error: 0.4548
Epoch 94/200
891/891 [==============================] - 0s 61us/step - loss: 0.1137 - mean_absolute_error: 0.4554
Epoch 95/200
891/891 [==============================] - 0s 67us/step - loss: 0.1137 - mean_absolute_error: 0.4548
Epoch 96/200
891/891 [==============================] - 0s 62us/step - loss: 0.1137 - mean_absolute_error: 0.4555
Epoch 97/200
891/891 [==============================] - 0s 66us/step - loss: 0.1137 - mean_absolute_error: 0.4535
Epoch 98/200
891/891 [==============================] - 0s 56us/step - loss: 0.1137 - mean_absolute_error: 0.4546
Epoch 99/200
891/891 [==============================] - 0s 63us/step - loss: 0.1137 - mean_absolute_error: 0.4541
Epoch 100/200
891/891 [==============================] - 0s 59us/step - loss: 0.1136 - mean_absolute_error: 0.4548
Epoch 101/200
891/891 [==============================] - 0s 61us/step - loss: 0.1137 - mean_absolute_error: 0.4553
Epoch 102/200
891/891 [==============================] - 0s 58us/step - loss: 0.1137 - mean_absolute_error: 0.4550
Epoch 103/200
891/891 [==============================] - 0s 74us/step - loss: 0.1137 - mean_absolute_error: 0.4550
Epoch 104/200
891/891 [==============================] - 0s 80us/step - loss: 0.1137 - mean_absolute_error: 0.4543
Epoch 105/200
891/891 [==============================] - 0s 89us/step - loss: 0.1137 - mean_absolute_error: 0.4549
Epoch 106/200
891/891 [==============================] - 0s 81us/step - loss: 0.1137 - mean_absolute_error: 0.4542
Epoch 107/200
891/891 [==============================] - 0s 82us/step - loss: 0.1137 - mean_absolute_error: 0.4541
Epoch 108/200
891/891 [==============================] - 0s 83us/step - loss: 0.1137 - mean_absolute_error: 0.4558
Epoch 109/200
891/891 [==============================] - 0s 87us/step - loss: 0.1137 - mean_absolute_error: 0.4544
Epoch 110/200
891/891 [==============================] - 0s 84us/step - loss: 0.1137 - mean_absolute_error: 0.4553
Epoch 111/200
891/891 [==============================] - 0s 81us/step - loss: 0.1137 - mean_absolute_error: 0.4561
Epoch 112/200
891/891 [==============================] - 0s 78us/step - loss: 0.1137 - mean_absolute_error: 0.4535
Epoch 113/200
891/891 [==============================] - 0s 73us/step - loss: 0.1137 - mean_absolute_error: 0.4550
Epoch 114/200
891/891 [==============================] - 0s 80us/step - loss: 0.1137 - mean_absolute_error: 0.4540
Epoch 115/200
891/891 [==============================] - 0s 85us/step - loss: 0.1137 - mean_absolute_error: 0.4548
Epoch 116/200
891/891 [==============================] - 0s 92us/step - loss: 0.1137 - mean_absolute_error: 0.4546
Epoch 117/200
891/891 [==============================] - 0s 75us/step - loss: 0.1137 - mean_absolute_error: 0.4551
Epoch 118/200
891/891 [==============================] - 0s 66us/step - loss: 0.1136 - mean_absolute_error: 0.4554
Epoch 119/200
891/891 [==============================] - 0s 59us/step - loss: 0.1137 - mean_absolute_error: 0.4550
Epoch 120/200
891/891 [==============================] - 0s 64us/step - loss: 0.1137 - mean_absolute_error: 0.4539
Epoch 121/200
891/891 [==============================] - 0s 55us/step - loss: 0.1137 - mean_absolute_error: 0.4546
Epoch 122/200
891/891 [==============================] - 0s 56us/step - loss: 0.1137 - mean_absolute_error: 0.4551
Epoch 123/200
891/891 [==============================] - 0s 58us/step - loss: 0.1137 - mean_absolute_error: 0.4545
Epoch 124/200
891/891 [==============================] - 0s 57us/step - loss: 0.1137 - mean_absolute_error: 0.4544
Epoch 125/200
891/891 [==============================] - 0s 62us/step - loss: 0.1137 - mean_absolute_error: 0.4548
Epoch 126/200
891/891 [==============================] - 0s 59us/step - loss: 0.1137 - mean_absolute_error: 0.4542
Epoch 127/200
891/891 [==============================] - 0s 63us/step - loss: 0.1137 - mean_absolute_error: 0.4540
Epoch 128/200
891/891 [==============================] - 0s 66us/step - loss: 0.1137 - mean_absolute_error: 0.4533
Epoch 129/200
891/891 [==============================] - 0s 68us/step - loss: 0.1137 - mean_absolute_error: 0.4555
Epoch 130/200
891/891 [==============================] - 0s 59us/step - loss: 0.1137 - mean_absolute_error: 0.4560
Epoch 131/200
891/891 [==============================] - 0s 72us/step - loss: 0.1137 - mean_absolute_error: 0.4546
Epoch 132/200
891/891 [==============================] - 0s 73us/step - loss: 0.1137 - mean_absolute_error: 0.4541
Epoch 133/200
891/891 [==============================] - 0s 71us/step - loss: 0.1137 - mean_absolute_error: 0.4552
Epoch 134/200
891/891 [==============================] - 0s 66us/step - loss: 0.1137 - mean_absolute_error: 0.4552
Epoch 135/200
891/891 [==============================] - 0s 73us/step - loss: 0.1137 - mean_absolute_error: 0.4550
Epoch 136/200
891/891 [==============================] - 0s 61us/step - loss: 0.1137 - mean_absolute_error: 0.4547
Epoch 137/200
891/891 [==============================] - 0s 58us/step - loss: 0.1137 - mean_absolute_error: 0.4551
Epoch 138/200
891/891 [==============================] - 0s 64us/step - loss: 0.1137 - mean_absolute_error: 0.4542
Epoch 139/200
891/891 [==============================] - 0s 60us/step - loss: 0.1137 - mean_absolute_error: 0.4549
Epoch 140/200
891/891 [==============================] - 0s 65us/step - loss: 0.1136 - mean_absolute_error: 0.4545
Epoch 141/200
891/891 [==============================] - 0s 62us/step - loss: 0.1137 - mean_absolute_error: 0.4552
Epoch 142/200
891/891 [==============================] - 0s 57us/step - loss: 0.1136 - mean_absolute_error: 0.4540
Epoch 143/200

891/891 [==============================] - 0s 63us/step - loss: 0.1137 - mean_absolute_error: 0.4542
Epoch 144/200
891/891 [==============================] - 0s 59us/step - loss: 0.1137 - mean_absolute_error: 0.4552
Epoch 145/200
891/891 [==============================] - 0s 62us/step - loss: 0.1137 - mean_absolute_error: 0.4546
Epoch 146/200
891/891 [==============================] - 0s 54us/step - loss: 0.1137 - mean_absolute_error: 0.4550
Epoch 147/200
891/891 [==============================] - 0s 66us/step - loss: 0.1137 - mean_absolute_error: 0.4547
Epoch 148/200
891/891 [==============================] - 0s 74us/step - loss: 0.1136 - mean_absolute_error: 0.4548
Epoch 149/200
891/891 [==============================] - 0s 73us/step - loss: 0.1136 - mean_absolute_error: 0.4544
Epoch 150/200
891/891 [==============================] - 0s 71us/step - loss: 0.1137 - mean_absolute_error: 0.4550
Epoch 151/200
891/891 [==============================] - 0s 78us/step - loss: 0.1137 - mean_absolute_error: 0.4546
Epoch 152/200
891/891 [==============================] - 0s 92us/step - loss: 0.1137 - mean_absolute_error: 0.4554
Epoch 153/200
891/891 [==============================] - 0s 138us/step - loss: 0.1137 - mean_absolute_error: 0.4546
Epoch 154/200
891/891 [==============================] - 0s 108us/step - loss: 0.1137 - mean_absolute_error: 0.4544
Epoch 155/200
891/891 [==============================] - 0s 107us/step - loss: 0.1136 - mean_absolute_error: 0.4558
Epoch 156/200
891/891 [==============================] - 0s 94us/step - loss: 0.1137 - mean_absolute_error: 0.4536
Epoch 157/200
891/891 [==============================] - 0s 106us/step - loss: 0.1137 - mean_absolute_error: 0.4549
Epoch 158/200
891/891 [==============================] - 0s 92us/step - loss: 0.1137 - mean_absolute_error: 0.4552
Epoch 159/200
891/891 [==============================] - 0s 76us/step - loss: 0.1137 - mean_absolute_error: 0.4552
Epoch 160/200
891/891 [==============================] - 0s 74us/step - loss: 0.1137 - mean_absolute_error: 0.4546
Epoch 161/200
891/891 [==============================] - 0s 81us/step - loss: 0.1136 - mean_absolute_error: 0.4543
Epoch 162/200
891/891 [==============================] - 0s 89us/step - loss: 0.1137 - mean_absolute_error: 0.4542
Epoch 163/200
891/891 [==============================] - 0s 78us/step - loss: 0.1137 - mean_absolute_error: 0.4547
Epoch 164/200
891/891 [==============================] - 0s 77us/step - loss: 0.1137 - mean_absolute_error: 0.4540
Epoch 165/200
891/891 [==============================] - 0s 101us/step - loss: 0.1137 - mean_absolute_error: 0.4555
Epoch 166/200
891/891 [==============================] - 0s 135us/step - loss: 0.1137 - mean_absolute_error: 0.4548
Epoch 167/200
891/891 [==============================] - 0s 110us/step - loss: 0.1137 - mean_absolute_error: 0.4535
Epoch 168/200
891/891 [==============================] - 0s 133us/step - loss: 0.1137 - mean_absolute_error: 0.4555
Epoch 169/200
891/891 [==============================] - 0s 87us/step - loss: 0.1137 - mean_absolute_error: 0.4561
Epoch 170/200
891/891 [==============================] - 0s 101us/step - loss: 0.1137 - mean_absolute_error: 0.4547
Epoch 171/200
891/891 [==============================] - 0s 93us/step - loss: 0.1137 - mean_absolute_error: 0.4549
Epoch 172/200
891/891 [==============================] - 0s 85us/step - loss: 0.1137 - mean_absolute_error: 0.4546
Epoch 173/200
891/891 [==============================] - 0s 79us/step - loss: 0.1137 - mean_absolute_error: 0.4544
Epoch 174/200
891/891 [==============================] - 0s 69us/step - loss: 0.1137 - mean_absolute_error: 0.4556
Epoch 175/200
891/891 [==============================] - 0s 72us/step - loss: 0.1137 - mean_absolute_error: 0.4544
Epoch 176/200
891/891 [==============================] - 0s 83us/step - loss: 0.1137 - mean_absolute_error: 0.4548
Epoch 177/200
891/891 [==============================] - 0s 83us/step - loss: 0.1137 - mean_absolute_error: 0.4551
Epoch 178/200
891/891 [==============================] - 0s 102us/step - loss: 0.1137 - mean_absolute_error: 0.4547
Epoch 179/200
891/891 [==============================] - 0s 90us/step - loss: 0.1137 - mean_absolute_error: 0.4545
Epoch 180/200
891/891 [==============================] - 0s 88us/step - loss: 0.1137 - mean_absolute_error: 0.4554
Epoch 181/200
891/891 [==============================] - 0s 69us/step - loss: 0.1137 - mean_absolute_error: 0.4550
Epoch 182/200
891/891 [==============================] - 0s 76us/step - loss: 0.1137 - mean_absolute_error: 0.4552
Epoch 183/200
891/891 [==============================] - 0s 79us/step - loss: 0.1137 - mean_absolute_error: 0.4550
Epoch 184/200
891/891 [==============================] - 0s 86us/step - loss: 0.1137 - mean_absolute_error: 0.4544
Epoch 185/200
891/891 [==============================] - 0s 79us/step - loss: 0.1137 - mean_absolute_error: 0.4541
Epoch 186/200
891/891 [==============================] - 0s 74us/step - loss: 0.1137 - mean_absolute_error: 0.4557
Epoch 187/200
891/891 [==============================] - 0s 77us/step - loss: 0.1137 - mean_absolute_error: 0.4542
Epoch 188/200
891/891 [==============================] - 0s 73us/step - loss: 0.1137 - mean_absolute_error: 0.4547
Epoch 189/200
891/891 [==============================] - 0s 66us/step - loss: 0.1136 - mean_absolute_error: 0.4540
Epoch 190/200
891/891 [==============================] - 0s 84us/step - loss: 0.1137 - mean_absolute_error: 0.4543
Epoch 191/200
891/891 [==============================] - 0s 155us/step - loss: 0.1136 - mean_absolute_error: 0.4552
Epoch 192/200
891/891 [==============================] - 0s 82us/step - loss: 0.1137 - mean_absolute_error: 0.4554
Epoch 193/200
891/891 [==============================] - 0s 76us/step - loss: 0.1137 - mean_absolute_error: 0.4551
Epoch 194/200
891/891 [==============================] - 0s 81us/step - loss: 0.1137 - mean_absolute_error: 0.4548
Epoch 195/200
891/891 [==============================] - 0s 91us/step - loss: 0.1137 - mean_absolute_error: 0.4538
Epoch 196/200
891/891 [==============================] - 0s 83us/step - loss: 0.1137 - mean_absolute_error: 0.4542
Epoch 197/200
891/891 [==============================] - 0s 78us/step - loss: 0.1137 - mean_absolute_error: 0.4554
Epoch 198/200
891/891 [==============================] - 0s 76us/step - loss: 0.1137 - mean_absolute_error: 0.4552
Epoch 199/200
891/891 [==============================] - 0s 82us/step - loss: 0.1137 - mean_absolute_error: 0.4542
Epoch 200/200
891/891 [==============================] - 0s 75us/step - loss: 0.1136 - mean_absolute_error: 0.4549

In [13]:
X_test = np.array(test[features])
X_test

array([[ 3.    , 34.5   ,  1.    ,  7.8292,  0.    ],
       [ 3.    , 47.    ,  0.    ,  7.    ,  0.    ],
       [ 2.    , 62.    ,  1.    ,  9.6875,  0.    ],
       ...,
       [ 3.    , 38.5   ,  1.    ,  7.25  ,  0.    ],
       [ 3.    , 29.    ,  1.    ,  8.05  ,  0.    ],
       [ 3.    , 29.    ,  1.    , 22.3583,  1.    ]])

In [14]:
predicciones = model.predict(X_test)
#print(predicciones)

In [15]:
predicciones = predicciones.tolist()

In [16]:
pre = pd.Series(predicciones)
validate['prediccion'] = pre
validate['prediccion'] = validate['prediccion'].str.get(0)
validate

     PassengerId  Survived  prediccion
0            892         0    0.304349
1            893         1    0.304349
2            894         0    0.304349
3            895         0    0.304349
4            896         1    0.304349
5            897         0    0.304349
6            898         1    0.304349
7            899         0    0.304349
8            900         1    0.304349
9            901         0    0.304349
10           902         0    0.304349
11           903         0    0.304349
12           904         1    0.304349
13           905         0    0.304349
14           906         1    0.304349
15           907         1    0.304349
16           908         0    0.304349
17           909         0    0.304349
18           910         1    0.304349
19           911         1    0.304349
20           912         0    0.304349
21           913         0    0.203562
22           914         1    0.304349
23           915         0    0.304349
24           916         1    0.304349
25           917         0    0.304349
26           918         1    0.304349
27           919         0    0.304349
28           920         0    0.304349
29           921         0    0.304349
..           ...       ...         ...
388         1280         0    0.304349
389         1281         0    0.304349
390         1282         0    0.304349
391         1283         1    0.304349
392         1284         0    0.304349
393         1285         0    0.304349
394         1286         0    0.304349
395         1287         1    0.304349
396         1288         0    0.304349
397         1289         1    0.304349
398         1290         0    0.304349
399         1291         0    0.304349
400         1292         1    0.304349
401         1293         0    0.304349
402         1294         1    0.304349
403         1295         0    0.304349
404         1296         0    0.304349
405         1297         0    0.304349
406         1298         0    0.304349
407         1299         0    0.304349
408         1300         1    0.304349
409         1301         1    0.304349
410         1302         1    0.304349
411         1303         1    0.304349
412         1304         1    0.304349
413         1305         0    0.304349
414         1306         1    0.304349
415         1307         0    0.304349
416         1308         0    0.304349
417         1309         0    0.304349

[418 rows x 3 columns]

In [17]:
coincidencias = []
for dato in validate.prediccion:
    if dato >= 0.5:
        coincidencias.append(1)
    else:
        coincidencias.append(0)
validate['final'] = coincidencias
validate

     PassengerId  Survived  prediccion  final
0            892         0    0.304349      0
1            893         1    0.304349      0
2            894         0    0.304349      0
3            895         0    0.304349      0
4            896         1    0.304349      0
5            897         0    0.304349      0
6            898         1    0.304349      0
7            899         0    0.304349      0
8            900         1    0.304349      0
9            901         0    0.304349      0
10           902         0    0.304349      0
11           903         0    0.304349      0
12           904         1    0.304349      0
13           905         0    0.304349      0
14           906         1    0.304349      0
15           907         1    0.304349      0
16           908         0    0.304349      0
17           909         0    0.304349      0
18           910         1    0.304349      0
19           911         1    0.304349      0
20           912         0    0.304349      0
21           913         0    0.203562      0
22           914         1    0.304349      0
23           915         0    0.304349      0
24           916         1    0.304349      0
25           917         0    0.304349      0
26           918         1    0.304349      0
27           919         0    0.304349      0
28           920         0    0.304349      0
29           921         0    0.304349      0
..           ...       ...         ...    ...
388         1280         0    0.304349      0
389         1281         0    0.304349      0
390         1282         0    0.304349      0
391         1283         1    0.304349      0
392         1284         0    0.304349      0
393         1285         0    0.304349      0
394         1286         0    0.304349      0
395         1287         1    0.304349      0
396         1288         0    0.304349      0
397         1289         1    0.304349      0
398         1290         0    0.304349      0
399         1291         0    0.304349      0
400         1292         1    0.304349      0
401         1293         0    0.304349      0
402         1294         1    0.304349      0
403         1295         0    0.304349      0
404         1296         0    0.304349      0
405         1297         0    0.304349      0
406         1298         0    0.304349      0
407         1299         0    0.304349      0
408         1300         1    0.304349      0
409         1301         1    0.304349      0
410         1302         1    0.304349      0
411         1303         1    0.304349      0
412         1304         1    0.304349      0
413         1305         0    0.304349      0
414         1306         1    0.304349      0
415         1307         0    0.304349      0
416         1308         0    0.304349      0
417         1309         0    0.304349      0

[418 rows x 4 columns]

In [18]:
coincide = 0
coincide = sum(validate['Survived'] == validate['final'])
print(coincide)
print(float(coincide)/ float(len(validate)))


match = 0
nomatch = 0
for val in validate.values:
    if val[1] == val[3]:
        match = match +1
    else:
        nomatch = nomatch +1
print(float(match)/float(len(validate)))

266
0.6363636363636364
0.6363636363636364

In [19]:
toKaggle = pd.DataFrame({'PassengerId':validate['PassengerId'],
                         'Survived':validate['final']})

toKaggle.head()

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

# output file with your prediction

In [20]:
from datetime import datetime
archivo = 'TitanicPred.csv'

toKaggle.to_csv(archivo,index=False)

print('Creado: ' + archivo)

Creado: Titanic012018-10-2818:28:10.csv